version: "3"
services:
  db:
    image: postgres:13.6-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_PASSWORD: 'password'
    ports:
      - 5450:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - db-connect
  server:
    build: .
    networks:
      - db-connect
    command: go run cmd/main.go
    depends_on:
      - db
    ports:
      - 8080:8080
    tty: true
    stdin_open: true
    environment:
      DATABASE_URL: postgres:password@tcp(db:5432)/king-tool-api?parseTime=true

volumes:
  database:
networks:
  db-connect:
    external: true
